language: php

dist: 'trusty'

php:
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - vendor/bin/phpunit analyze -l 4 src/
  - vendor/bin/phpunit
