language: php

dist: 'trusty'

php:
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - vendor/bin/phpunit
  - composer require --dev illuminate/support && vendor/bin/phpstan analyze --no-progress --autoload-file=tests/phpstan/bootstrap.php --level=5 src/
